### ISSUE TITLE
Crash after when starting first trainer fight

### ISSUE THREAD

**Issue by CupricReki** [lxgr-linux/pokete#1]
Fought in tall grass just below start
Tried to catch the rat unsuccessful about 10 times - always said missed even though it looked like it just escaped
Killed it
Healed at center
Encountered trainer
Crash

`Traceback (most recent call last):
File "/home/cupric/tmp/./pokete/pokete.py", line 1407, in <module>
main()
File "/home/cupric/tmp/./pokete/pokete.py", line 980, in main
File "/home/cupric/tmp/./pokete/pokete.py", line 937, in game
figure.set(figure.x+x, figure.y+y)
File "/home/cupric/tmp/pokete/scrap_engine.py", line 162, in set
File "/home/cupric/tmp/./pokete/pokete.py", line 155, in action
game(self.arg_proto["map"])
File "/home/cupric/tmp/./pokete/pokete.py", line 937, in game
File "/home/cupric/tmp/pokete/scrap_engine.py", line 162, in set
ob.action(self)
File "/home/cupric/tmp/./pokete/pokete.py", line 146, in action
trainer.do(map)
File "/home/cupric/tmp/./pokete/pokete.py", line 91, in do
winner = fight([poke for poke in figure.pokes[:6] if poke.hp > 0][0], self.poke, info={"type": "duel", "player": self})
File "/home/cupric/tmp/./pokete/pokete.py", line 721, in fight
attack = ob.attac_obs[int(eval(ev))]`

**Comment by lxgr-linux** [comment]
I see what the problem is, you might have tried to use an attack that's not available yet.

**Comment by lxgr-linux** [comment]
This should fix the issue. The chance to catch a pokete increases the lover the poketes health is. So it's nearly impossible to catch it at full health. But at 1/2 HP it's pretty easy.
