### ISSUE TITLE
Game crashed in starting town after winning a fight

### ISSUE THREAD

**Issue by magnus-ISU** [lxgr-linux/pokete#177]
**Checklist**
I have:
- [X] Searched the Issues page for my problem/feature request
- [X] Updated all related software and Pokete it self

**Describe the bug**
Game crashed in starting town after winning a fight
It seems to be leveling up that does it

**To Reproduce**
Level up

**Expected behavior**
No crash

Commenting out the line seems to work, and it sounds like its aesthetic. I don't know the structure of the classes to do a real fix

**Screenshots**
Traceback (most recent call last):
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1543, in <module>
    main()
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1200, in main
    game.game(figure.map)
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1022, in _game
    figure.set(figure.x + x, figure.y + y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 58, in action
    super().action(ob)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 40, in action
    game.game(obmp.ob_maps[self.arg_proto["map"]])
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1022, in _game
    figure.set(figure.x + x, figure.y + y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 25, in action
    game.game(ob.map)
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1022, in _game
    figure.set(figure.x + x, figure.y + y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 58, in action
    super().action(ob)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 40, in action
    game.game(obmp.ob_maps[self.arg_proto["map"]])
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1022, in _game
    figure.set(figure.x + x, figure.y + y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 25, in action
    game.game(ob.map)
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1022, in _game
    figure.set(figure.x + x, figure.y + y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 58, in action
    super().action(ob)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 40, in action
    game.game(obmp.ob_maps[self.arg_proto["map"]])
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1022, in _game
    figure.set(figure.x + x, figure.y + y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/doors.py", line 25, in action
    game.game(ob.map)
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1022, in _game
    figure.set(figure.x + x, figure.y + y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/landscape.py", line 30, in action
    fm.fightmap.fight(
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/fightmap.py", line 386, in fight
    winner.moves.shine()
AttributeError: 'Figure' object has no attribute 'moves'. Did you mean: 'pokes'?

**Environment**
 - OS: Arch Linux
 - Pokete version: 0.7.2
 - Python version: 3.10.5
 - Scrap engine version: AUR git package

**Additional context**

**Comment by jlultimate** [comment]
I got this too! This is so weird
