### ISSUE TITLE
Unsure if this is just intended, but a cheese strat to beat Confuso

### ISSUE THREAD

**Issue by magnus-ISU** [lxgr-linux/pokete#206]
His attacks only confuse your pokemon.

Thus, you can just keep switching between your pokes until he runs out of AP

Personally, I think its funny and should stay in the game

**Comment by magnus-ISU** [comment]
This of course assumes you fix the crash bug related to an enemy running out of attacks which I tried to tell you in my last issue.

```
Traceback (most recent call last):
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1548, in <module>
    main()
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1199, in main
    game.game(figure.map)
  File "/home/mag/Documents/code/gamedev/random/pokete/./pokete.py", line 1024, in _game
    figure.set(figure.x + action.get_X_strength(), figure.y + action.get_Y_strength())
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/npcs.py", line 32, in action
    self.npc.action()
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/npcs.py", line 252, in action
    winner = fm.fightmap.fight(
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/fightmap.py", line 390, in fight
    self.add_1(*providers)
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/fightmap.py", line 111, in add_1
    enem.curr.tril,
  File "/home/mag/Documents/code/gamedev/random/pokete/pokete_classes/providers.py", line 15, in curr
    return self.pokes[self.play_index]
IndexError: list index out of range
```

I'm refactoring the fight code and will fix this with that

**Comment by lxgr-linux** [comment]
Yes, this was intended, and I thought the errormessage in the other issue was different.
I'm looking forward to your refactor.

**Comment by greatericontop** [comment]
I really wouldn't call this a cheese, since any confusion-immune poketes (gobost, etc) just can't be confused anyway. The confuso has no other abilities anyway.

**Comment by lxgr-linux** [comment]
That may be the better option.

**Comment by cognivore** [comment]
I have beaten Confuso with gobost, but your strat is absolutely viable. I think it's more of a puzzle than anything else, and good job on finding an elegant strat!
