### ISSUE TITLE
Trying to containerize without audio enabled

### ISSUE THREAD

**Issue by quella** [lxgr-linux/pokete#244]
**Is your feature request related to a problem? Please describe.**
I'm desiring to covntanizerize the Python application and am running into audio issue.  It would be good to have a command line argument to disable audio on start up to prevent these errors, if possible.  When I execute the application in the container and it attempts to play audio I get the following errors.

Traceback (most recent call last):
File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrapself.run()
File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs)
File "/pokete_classes/audio.py", line 17, in audio_fn import playsound
File "/playsound/__init__.py", line 15, in <module> _playsound = ctypes.cdll.LoadLibrary(
File "/usr/local/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary return self._dlltype(name)
File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__

Also, if there is a good working directory that I should configure for saves, etc.

Thanks for all your work.

**Comment by lxgr-linux** [comment]
> Is your feature request related to a problem? Please describe.
I'm desiring to covntanizerize the Python application and am running into audio issue. It would be good to have a command line argument to disable audio on start up to prevent these errors, if possible. When I execute the application in the container and it attempts to play audio I get the following errors.
>
> Traceback (most recent call last):
File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrapself.run()
File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs)
File "/pokete_classes/audio.py", line 17, in audio_fn import playsound
File "/playsound/init.py", line 15, in _playsound = ctypes.cdll.LoadLibrary(
File "/usr/local/lib/python3.9/ctypes/init.py", line 452, in LoadLibrary return self._dlltype(name)
File "/usr/local/lib/python3.9/ctypes/init.py", line 374, in init

Oh, yes
I already thought about adding this and will do so soon.

> Thanks for all your work.

Thanks a lot

> Also, if there is a good working directory that I should configure for saves, etc.

You can easily configure the folder saves etc. will go in with the `XDG_DATA_HOME` environment variable.

Cheers

**Comment by quella** [comment]
Great to hear.  Looking forward to the future progress.  Thanks for all your efforts.
