### ISSUE TITLE
Pokete randomly crushing while in battle

### ISSUE THREAD

**Issue by Orest58008** [lxgr-linux/pokete#259]
**Checklist**
I have:
- [x] Searched the Issues page for my problem/feature request
- [x] Updated all related software and Pokete it self

**Describe the bug**
```
Traceback (most recent call last):
  File "/usr/bin/pokete", line 1667, in <module>
    main()
  File "/usr/bin/pokete", line 1304, in main
    _game(game_map)
  File "/usr/bin/pokete", line 1124, in _game
    figure.set(
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 283, in set
    obj.action(self)
  File "/usr/share/pokete/pokete_classes/npcs.py", line 31, in action
    self.npc.action()
  File "/usr/share/pokete/pokete_classes/npcs.py", line 275, in action
    winner = fm.fightmap.fight(
  File "/usr/share/pokete/pokete_classes/fightmap/__init__.py", line 324, in fight
    attack = player.get_attack(self, enem)
  File "/usr/share/pokete/pokete_classes/providers.py", line 116, in get_attack
    return fightmap.get_figure_attack(self, enem)
  File "/usr/share/pokete/pokete_classes/fightmap/__init__.py", line 262, in get_figure_attack
    item = self.invbox(self, items, figure.inv)
  File "/usr/share/pokete/pokete_classes/fightmap/inv.py", line 29, in __call__
    with self.add(_map, _map.width - 35, 0):
  File "/usr/share/pokete/pokete_classes/ui_elements.py", line 93, in add
    super().add(_map, x, y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 558, in add
    obj.add(self.map, obj.rx + self.x, obj.ry + self.y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 558, in add
    obj.add(self.map, obj.rx + self.x, obj.ry + self.y)
  File "/usr/lib/python3.10/site-packages/scrap_engine.py", line 246, in add
    raise CoordinateError(self, _map, x, y)
scrap_engine.CoordinateError: The <scrap_engine.Object object at 0x7fe10667b0a0>s coordinate (137|54) is not in 171x44
```

**To Reproduce**
Sometimes it happens when I open inventory and sometimes when I attack.

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Arch Linux
 - Pokete version: 0.9.0-1(`pokete` package in AUR)
 - Python version: 3.10.10-1
 - Scrap engine version: 1.4.0-1

**Additional context**
I changed my terminal's font size but it takes a while between it and the crash so I don't know if that is the cause

**Comment by lxgr-linux** [comment]
Oh yes, I can reproduce.

**Comment by lxgr-linux** [comment]
Thanks for reporting this, I found and fixed the bug and it would be nice if you could verify that at #260.

**Comment by Orest58008** [comment]
Changing font size amidst the battle still results in the same error.

**Comment by Orest58008** [comment]
Sorry, I accidentally pressed the wrong button

**Comment by Orest58008** [comment]
Thanks, that fixed the issue
