### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by iceguru** [lxgr-linux/pokete#295]
**Checklist**
I have:
- [Y ] Searched the Issues page for my problem/feature request
- [ Y] Updated all related software and Pokete it self

**Describe the bug**
Traceback (most recent call last):
  File "/Users/nobody1/./pokete/pokete.py", line 63, in <module>
    from util.command import RootCommand, Flag
  File "/Users/nobody1/pokete/util/command/__init__.py", line 1, in <module>
    from .command import Command, RootCommand, Flag
  File "/Users/nobody1/pokete/util/command/command.py", line 37
    f"\t{line[0]}{" " * (line_spaces - len(line[0]))}{line[1]}" for line
                                                                ^
SyntaxError: f-string: expecting '}'

**To Reproduce**
Ran the start cmd

**Expected behavior**
THe game to start

**Screenshots**
Traceback (most recent call last):
  File "/Users/nobody1/./pokete/pokete.py", line 63, in <module>
    from util.command import RootCommand, Flag
  File "/Users/nobody1/pokete/util/command/__init__.py", line 1, in <module>
    from .command import Command, RootCommand, Flag
  File "/Users/nobody1/pokete/util/command/command.py", line 37
    f"\t{line[0]}{" " * (line_spaces - len(line[0]))}{line[1]}" for line
                                                                ^
SyntaxError: f-string: expecting '}'

**Environment**
 - OSx
 - Recent
 - 3.12.4
 - 1.4.1
**Additional context**

**Comment by lxgr-linux** [comment]
Hello,
are you sure you're on python 3.12.x because that crash should only happen on python 3.11 and prior.

**Comment by iceguru** [comment]
You're right. Apparently I have differrent versions installed. brew said 3.12.4 but pip says 3.9

Guess I get to figure that out.

**Comment by iceguru** [comment]
Even right click open with the right 3.12.4 doesn't work. Same error.

**Comment by lxgr-linux** [comment]
That's really interesting. Can you try to run it from ur terminal?

```bash
python3 --version
python3 <path/to/pokete.py>
```
